### ISSUE TITLE
Gsh files

### ISSUE THREAD

**Issue by Elias6970** [bartlomiejduda/EA-Graphics-Manager#3]
Hi, I'm trying to convert gsh images from "fifa09 All play" for wii. Do you have any other way to speak about it like discord?
I have many questions and maybe you can solve it.

**Comment by jlnhlfan** [comment]
I tried opening one of those files from NHL 06, but was so delightfully greeted with this error message.
![Screenshot_June_07_2024_10_33_31_AM](https://github.com/bartlomiejduda/EA-Graphics-Manager/assets/31529087/b647e621-bfc9-4021-9b65-dad924bd52a6)

**Comment by bartlomiejduda** [comment]
@Elias6970 Those GSH files from "fifa09 All play" (WII) should be supported now in the newest **v0.19.8 release**, at least for parsing, preview/export may still by buggy sometimes. If you want, you can attach some samples and I'll look at them later.

@jlnhlfan Yes, that is valid error message for files that are currently not supported. There are two types of EA images. Type 1 (signatures SHPS/SHPX etc.) are supported and type 2 (signatures ShpS, ShpX etc.) are not supported yet.
They need completely new logic in the code to be parsed properly, because they have different file structure.
Support may be added in the future releases, please be patient.
