### ISSUE TITLE
MSH files on psp

### ISSUE THREAD

**Issue by reeshmd23** [bartlomiejduda/EA-Graphics-Manager#4]
Trying to open msh graphic files for editing on psp.  Can you take a look?  Trying to update sports games.  Heres some example files.
[head_jlam.zip](https://github.com/bartlomiejduda/EA-Graphics-Manager/files/11970208/head_jlam.zip)
[FALH.zip](https://github.com/bartlomiejduda/EA-Graphics-Manager/files/11970217/FALH.zip)

**Comment by bartlomiejduda** [comment]
Hi. What games are those samples from?

**Comment by reeshmd23** [comment]
Head msh file is fight night round 3
Falh msh is Madden 08 uniform

Opening them this way works just a pain.
https://forum.xentax.com/viewtopic.php?t=13031

**Comment by bartlomiejduda** [comment]
Ok, I'll check out those files.

**Comment by reeshmd23** [comment]
Do you have a discord?

**Comment by bartlomiejduda** [comment]
Yes, I have, but I don't share it too often. I prefer talking about technical details in public.

**Comment by kinglalu** [comment]
> Yes, I have, but I don't share it too often. I prefer talking about technical details in public.

Hey, so theres a modding community surrounded around EA's NHL 07 on the PSP, and your expertise could be incredibly helpful for figuring this out so that EA Graphic Manager can open PSP files, as the existing way to edit msh files for PSP is long and tedious. Your help could also be incredibly useful in asking other things regarding EA's file formats and such too, so I hope you would consider joining so we could easily ask questions we have. Here's a link to the discord if your interested 

https://discord.gg/8T6443EQvV

**Comment by bartlomiejduda** [comment]
Sure, I've just joined, but I can't promise that I will be an active member there. ;)

**Comment by bartlomiejduda** [comment]
@reeshmd23  So I've tested once again files **FALH.msh** and **head_jlam.msh** from the first post in the newest **v0.19.8** release of EA Graphics Manager and they can be previewed and exported just fine. :)
I'm closing this request.
